Npm
fintechstudios/eslint-plugin-chai-as-promised pull request #3
Opened 2020-02-23 05:45 UTC by brettz9

Builds on #2

- npm: Update devDeps (eslint, mocha) (thereby also avoiding their vulnerabilities)

2020-02-24 15:40 UTC, dpraul requested changes

2020-02-24 15:40 UTC, dpraul commented on package.json
>      "node": ">=0.10.0"
mocha 7 and eslint 6 require node versions over `^8.10.0`, but this is fine - we can do a major version bump. 

```suggestion
    "node": ">=8.10.0"
```

2020-02-24 22:16 UTC, brettz9 commented
I've applied the version bump.

Btw, if you want to simplify the README steps a little, it could be changed to include both installs as part of one install command:

```shell
npm install eslint @fintechstudios/eslint-plugin-chai-as-promised --save-dev
```

2020-02-25 15:18 UTC, dpraul approved these changes

2020-02-25 15:20 UTC, dpraul commented
Thanks for the improvements! And I'm fine with the README being a little verbose - in fact, I believe it follows the exact same format as eslint suggests for plugin repos (albeit, their suggestion from a while ago when this repo was made)

2020-02-25 15:21 UTC, merged